# Generated by Django 4.2.2 on 2023-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graft',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
