# Generated by Django 4.2.1 on 2023-05-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BGC_Back_End", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graft",
            name="category",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="graft",
            name="regulation",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
