# Generated by Django 4.2.2 on 2023-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graft',
            name='image',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='graft',
            name='purchase_link',
            field=models.URLField(blank=True),
        ),
    ]
