# Generated by Django 4.2.2 on 2023-11-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0002_alter_graft_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
