# Generated by Django 4.2.2 on 2023-12-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0004_graft_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
