# Generated by Django 4.2.2 on 2023-12-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0006_alter_graft_id_alter_graft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
