# Generated by Django 4.2.2 on 2023-12-23 20:54

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0008_alter_graft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='image',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='grafts/images/'),
        ),
    ]
