# Generated by Django 4.2.2 on 2023-08-03 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0009_graft_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
