# Generated by Django 4.2.2 on 2023-08-14 21:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0011_alter_graft_purchase_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='graft',
            name='image',
            field=models.FileField(null=True, upload_to='grafts/images'),
        ),
    ]
