# Generated by Django 4.2.2 on 2023-08-14 23:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0015_alter_graft_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
