# Generated by Django 4.2.2 on 2023-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0007_alter_graft_created_by_alter_graft_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='graft',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
