# Generated by Django 4.2.2 on 2023-08-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BGC_Back_End', '0010_alter_graft_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graft',
            name='purchase_link',
            field=models.CharField(blank=True),
        ),
    ]
